on:
  push:
    branches:
      - main

concurrency:
  group: openfn-deployment
  cancel-in-progress: false

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    permissions:
      contents: write
    steps:
      - name: openfn deploy
        uses: openfn/cli-deploy-action@v1
        with:
          secret_input: ${{ secrets.OPENFN_fd0d370e_83e1_4018_8f0b_73a3da535ad5_API_KEY }}
          config_path_input: 'openfn-fd0d370e-83e1-4018-8f0b-73a3da535ad5-config.json'
